name: Add new codelab

on:
  workflow_call:
  repository_dispatch:
    types: [gdocs_add]

jobs:
  add_codelab:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      CODELAB_ID: ${{ github.event.client_payload.documentId }}
      CODELAB_SOURCE: ${{ github.event.client_payload.codelabId }}
      CODELABS_JSON: codelabs.json
    steps:
      - uses: actions/checkout@v4

      - name: Add a new codelab
        run: |
          if [[ -z "${{ env.CODELAB_SOURCE }}" || -z "${{ env.CODELAB_ID }}" ]]; then
              echo "Error: Source and ID values are mandatory."
              exit 1
          fi
          if [ ! -f "${{ env.CODELABS_JSON }}" ]; then
              touch ${{ env.CODELABS_JSON }}
          fi
          if jq '.[] | select(.id == "${{ env.CODELAB_ID }}" or .source == "${{ env.CODELAB_SOURCE }}")' codelabs.json >/dev/null 2>&1; then
              echo "Entry with id: $id or source: ${{ env.CODELAB_SOURCE }} already exists!"
          else
              new_entry="{\"id\": \"${{ env.CODELAB_ID }}\", \"source\": \"${{ env.CODELAB_SOURCE }}\"}"
              jq -r ". += [$new_entry]" ${{ env.CODELABS_JSON }} > temp.json && mv temp.json ${{ env.CODELABS_JSON }}
              echo "Successfully added entry with id: $id and source: ${{ env.CODELAB_SOURCE }}"
          fi

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add codelabs.json
          git commit -m "Update codelabs.json" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
