name: Export gdocs

on:
  workflow_dispatch:
  push:
    # paths:
    #   - 'codelabs-md/*'

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
    export_codelabs:
        runs-on: ubuntu-latest
        env:
            CLAAT_VERSION: "v2.2.6"
        steps:
        - uses: actions/checkout@v4

        - name: get claat (latest)
          run: |
            go version
            export PATH=$PATH:$(go env GOPATH)/bin
            mkdir -p $(go env GOPATH)/bin
            curl -L -o $(go env GOPATH)/bin/claat https://github.com/googlecodelabs/tools/releases/download/${{env.CLAAT_VERSION}}/claat-linux-amd64
            chmod +x $(go env GOPATH)/bin/claat
            claat version
            echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

        - name: check codelabs directory
          run: |
            if [ ! -d codelabs ]; then
                mkdir codelabs
            fi

        - name: test export
          env:
            CLAAT_AUTH_CODE: ${{ secrets.CLAAT_AUTH_CODE }}
          working-directory: codelabs
          run: claat export -auth "${{ env.CLAAT_AUTH_CODE }}" 1al07Cg0AUmvb4FXd35KCQT1VvdRU7cGlrEEMdKqgo1I