name: Export gdocs

on:
  workflow_dispatch:
  push:
    # paths:
    #   - 'codelabs-md/*'

concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
    export_codelabs:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: get claat (latest)
          run: |
            go version
            go install github.com/googlecodelabs/tools/claat@latest
        
        - name: claat config
          env:
            CLAAT_CRED: ${{ secrets.CLAAT_CREDENTIALS }}
          run: |
            if [ ! -d ~/.config/claat ]; then
                mkdir -p ~/.config/claat
                echo $CLAAT_CRED > -p ~/.config/claat/goog-cred.json
            fi

        - name: check codelabs directory
          run: |
            if [ ! -d codelabs ]; then
                mkdir codelabs
            fi

        - name: test export
          working-directory: codelabs
          run: claat export 1al07Cg0AUmvb4FXd35KCQT1VvdRU7cGlrEEMdKqgo1I