name: Export gdocs

on:
  workflow_dispatch:
  push:
    # paths:
    #   - 'codelabs-md/*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  export_codelabs:
    permissions:
        contents: 'read'
        id-token: 'write'
    runs-on: ubuntu-latest
    env:
      CLAAT_VERSION: "v2.2.6"
    steps:
      - uses: actions/checkout@v4

      - name: Export Go bin to all steps
        id: go-env
        run: |
          go version
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          echo "go-bin-path=$(go env GOPATH)/bin" >> "$GITHUB_OUTPUT"

      # Save/Restore claat
      - name: claat cache
        uses: actions/cache@v4
        id: claat-cache
        with:
          path: |
            ${{ steps.go-env.outputs.go-bin-path }}/*
          key: go-claat

      - name: get claat (latest)
        if: steps.claat-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p $(go env GOPATH)/bin
          curl -L -o $(go env GOPATH)/bin/claat https://github.com/googlecodelabs/tools/releases/download/${{env.CLAAT_VERSION}}/claat-linux-amd64
          chmod +x $(go env GOPATH)/bin/claat
          claat version

      - name: Reset codelabs directory
        run: |
          if [ -d codelabs ]; then
              rm -rf codelabs
          else
              mkdir codelabs
          fi

      - name: Generate Oauth2 token
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
            token_format: 'access_token'
            access_token_scopes: 'https://www.googleapis.com/auth/drive.readonly'
            credentials_json: '${{ secrets.SERVICE_ACCOUNT_CREDS }}'

      - name: Test export
        working-directory: codelabs
        run: claat export -auth "${{ steps.auth.outputs.access_token }}" 1al07Cg0AUmvb4FXd35KCQT1VvdRU7cGlrEEMdKqgo1I
