name: Export gdocs

on:
  workflow_dispatch:
  push:
    paths:
      - "codelabs.json"
      - "./github/workflows/*"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  export_codelabs:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    env:
      CLAAT_VERSION: "v2.2.6"
      GA_ID: "UA-3295395-7"
      GA_ID_V4: "G-E0H6JSF2N3"
    steps:
      - uses: actions/checkout@v4

      - name: Export Go bin to all steps
        id: go-env
        run: |
          go version
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          echo "go-bin-path=$(go env GOPATH)/bin" >> "$GITHUB_OUTPUT"

      # Save/Restore claat
      - name: claat cache
        uses: actions/cache@v4
        id: claat-cache
        with:
          path: |
            ${{ steps.go-env.outputs.go-bin-path }}/*
          key: go-claat

      # - name: get claat (latest)
      #   if: steps.claat-cache.outputs.cache-hit != 'true'
      #   run: |
      #     mkdir -p $(go env GOPATH)/bin
      #     curl -L -o $(go env GOPATH)/bin/claat https://github.com/googlecodelabs/tools/releases/download/${{env.CLAAT_VERSION}}/claat-linux-amd64
      #     chmod +x $(go env GOPATH)/bin/claat
      #     claat version

      - name: get claat (latest)
        if: steps.claat-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p $(go env GOPATH)/bin
          go install github.com/googlecodelabs/tools/claat@latest
          claat version

      - name: Reset codelabs directories
        run: |
          if [ -d codelabs ]; then
              rm -rf codelabs
          fi
          if [ -d codelabs-md ]; then
              rm -rf codelabs-md
          fi
          mkdir codelabs
          mkdir codelabs-md

      - name: Generate Oauth2 token
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          access_token_scopes: "https://www.googleapis.com/auth/drive.readonly"
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_CREDS }}"

      - name: Export all codelabs
        run: |
          sources=$(cat codelabs.json | grep "source" | sed 's/.*": "\(.*\)"/\1/')
          while read line; do
              claat export -ga ${{ env.GA_ID }} -o "codelabs/" -auth "${{ steps.auth.outputs.access_token }}" $line
              claat export -ga ${{ env.GA_ID }} -o "codelabs-md/" -f "md" -auth "${{ steps.auth.outputs.access_token }}" $line
          done <<< "$sources"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add codelabs/* codelabs-md/*
          git commit -m "Export codelabs $(date '+%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
