name: demo claat

on:
  workflow_dispatch:

jobs:
  demo-claat-action:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    env:
      CLAAT_VERSION: "v2.2.6"
      GA_ID: "UA-3295395-7"
      GA_ID_V4: "G-E0H6JSF2N3"
      HTML_PATH: codelabs
      MD_PATH: codelabs-md
    steps:
      - uses: actions/checkout@v4

      - name: Generate Oauth2 token
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          access_token_scopes: "https://www.googleapis.com/auth/drive.readonly"
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_CREDS }}"

      - name: claat
        uses: ./actions/claat
        with:
          auth: ${{ steps.auth.outputs.access_token }}
          source: 1al07Cg0AUmvb4FXd35KCQT1VvdRU7cGlrEEMdKqgo1I
          codelabs-path: demo

      - name: claat
        uses: ./actions/claat
        with:
          auth: ${{ steps.auth.outputs.access_token }}
          source: 1al07Cg0AUmvb4FXd35KCQT1VvdRU7cGlrEEMdKqgo1I
          codelabs-path: demo
          codelabs-json: codelabs.json
