name: Trigger build on external workflow

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Export gdocs]
    types: [completed]

jobs:
  trigger:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CE_MAIN_REPO_ACCESS_TOKEN }}
          script: |
            const owner = 'khammami'
            const repo = 'codelabs-enetcom'

            github.rest.repos.createDispatchEvent({
              owner,
              repo,
              event_type: 'dispatch_build',
              client_payload: {
                message: 'Triggering build from codelabs workflow!'
              }
            })
