name: Export gdocs

on:
  workflow_dispatch:
  repository_dispatch:
    types: [gdocs_export,gdocs_export_all]
  push:
    paths:
      - "codelabs.json"

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  export_codelabs:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    env:
      CLAAT_VERSION: "v2.2.6"
      GA_ID: "UA-3295395-7"
      GA_ID_V4: "G-E0H6JSF2N3"
      HTML_PATH: codelabs
      MD_PATH: codelabs-md
    steps:
      - uses: actions/checkout@v4

      - name: Generate Oauth2 token
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          token_format: "access_token"
          access_token_scopes: "https://www.googleapis.com/auth/drive.readonly"
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_CREDS }}"

      - name: claat export all documents in codelabs.json
        uses: ./actions/claat
        with:
          auth: ${{ steps.auth.outputs.access_token }}
          document-id: 1al07Cg0AUmvb4FXd35KCQT1VvdRU7cGlrEEMdKqgo1I
          codelabs-path: ${{ env.HTML_PATH }}
          codelabs-json: codelabs.json
          format: all

      - name: Check for worktree changes
        id: git-changes
        run: |
          [ "$(git status --porcelain=v1 2>/dev/null | wc -l)" -gt 0 ] && \
          echo "is-changed=true" || echo "is-changed=false" >> "$GITHUB_OUTPUT"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add ${{ env.HTML_PATH }}/* ${{ env.MD_PATH }}/*
          git commit -m "Export codelabs $(date '+%Y-%m-%d %H:%M')" || echo "No changes to commit"
          git push origin || echo "No changes to commit"

      - name: Dispatch build on main repo
        if: steps.git-changes.outputs.is-changed == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CE_MAIN_REPO_ACCESS_TOKEN }}
          script: |
            const owner = 'khammami'
            const repo = 'codelabs-enetcom'

            github.rest.repos.createDispatchEvent({
              owner,
              repo,
              event_type: 'dispatch_build',
              client_payload: {
                message: 'Triggering build from codelabs workflow!'
              }
            })
